### ISSUE TITLE
Incorrect mode calculation and value

### ISSUE THREAD

**Issue by MarkShark99** [jennyjiangke/book#1]
The `getMode()` function defined in `03-Statistical_Analyses_of_a_Single_Variable.Rmd`, when given a vector that doesn't contain a repeating number, will return the first value in that vector. This can be seen in Table 3.9 since the 'Sessions' column in the sample data doesn't have a mode.

The mode also appears to be incorrectly listed as 3787 on line 357.

https://github.com/jennyjiangke/book/blob/f002ac60483b68c25febce59111384d7fc77b57e/03-Statistical_Analyses_of_a_Single_Variable.Rmd#L292

https://github.com/jennyjiangke/book/blob/f002ac60483b68c25febce59111384d7fc77b57e/03-Statistical_Analyses_of_a_Single_Variable.Rmd#L357

**Comment by jennyjiangke** [comment]
Thank you so much for your suggestions!
